# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Weatehr")
        MainWindow.resize(500, 550)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: QLinearGradient(x1: 1, y1: 1, \n"
"                            x2: 0, y2: 0, \n"
"                            stop: 0   #ffffff, \n"
"                            stop: 0.3 rgba(102, 181, 255, 200), \n"
"                            stop: 1   #24903f);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 160, 450, 250))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: QLinearGradient(x1: 1, y1: 1, \n"
"                            x2: 0, y2: 0, \n"
"                            stop: 0   #4548ff, \n"
"                            stop: 0.3 rgba(102, 181, 255, 200), \n"
"                            stop: 1   #67ff3d);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid#ffffff;\n"
"border-radius:15;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 470, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient(x1: 1, y1: 1, \n"
"                            x2: 0, y2: 0, \n"
"                            stop: 0   #4548ff, \n"
"                            stop: 0.3 rgba(102, 181, 255, 200), \n"
"                            stop: 1   #67ff3d);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid#ffffff;\n"
"    border-radius: 15;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: QLinearGradient(x1: 1, y1: 1, \n"
"                            x2: 0, y2: 0, \n"
"                            stop: 0   #459cff, \n"
"                            stop: 0.3 rgba(102, 181, 255, 200), \n"
"                            stop: 1   #3dff94);\n"
"    \n"
"    \n"
"    \n"
"    color: rgb(213, 213, 213);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(25, 100, 450, 45))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setStyleSheet("background: QLinearGradient(x1: 1, y1: 1, \n"
"                            x2: 0, y2: 0, \n"
"                            stop: 0   #4548ff, \n"
"                            stop: 0.3 rgba(102, 181, 255, 200), \n"
"                            stop: 1   #67ff3d);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid#ffffff;\n"
"border-radius:15;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 441, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("\n"
"border-radius:30;\n"
"color: rgb(229, 229, 229);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Weatehr", "Weatehr"))
        self.label.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "Дізнатись погоду"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введіть місто..."))
        self.label_2.setText(_translate("MainWindow", "Weather today"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
